# Generated by Django 2.2.3 on 2021-09-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='权限名')),
                ('param_json', models.TextField(verbose_name='参数限制')),
                ('req_info', models.TextField(default=None, verbose_name='传入参数')),
                ('need_login', models.BooleanField(default=False, verbose_name='是否需要登录')),
                ('is_allow', models.BooleanField(default=True, verbose_name='是否允许请求')),
                ('call_limit', models.IntegerField(default=-1, verbose_name='请求次数上限')),
            ],
            options={
                'verbose_name': '权限信息',
                'verbose_name_plural': '权限信息',
                'db_table': 'vp_permissions',
            },
        ),
        migrations.CreateModel(
            name='ViewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=50, verbose_name='视图名')),
                    ('name', models.CharField(max_length=50, verbose_name='权限名')),
                ('url', models.CharField(max_length=50, verbose_name='URL')),
                ('method', models.CharField(
                    choices=[('1', 'GET'), ('2', 'POST'), ('3', 'PUT'), ('4', 'PATCH'), ('5', 'DELETE'), ('6', 'HEAD'),
                             ('7', 'OPTIONS'), ('8', 'TRACE')], max_length=50, verbose_name='请求方式')),
                ('comment', models.TextField(default='')),
                ('param_json', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '视图信息',
                'verbose_name_plural': '视图信息',
                'db_table': 'vp_views',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('contain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='view_permission.UserGroup', verbose_name='完全包含的VIP组')),
                ('view_permissions',
                 models.ManyToManyField(blank=True, to='view_permission.PermissionModel', verbose_name='视图权限')),
            ],
            options={
                'verbose_name': '权限组',
                'verbose_name_plural': '权限组',
                'db_table': 'vp_groups',
            },
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='view_permission.ViewModel'),
        ),
    ]
