# Generated by Django 2.2.3 on 2021-09-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='is_allow',
            field=models.BooleanField(default=True, verbose_name='是否允许请求'),
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='need_login',
            field=models.BooleanField(default=False, verbose_name='是否需要登录'),
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='req_info',
            field=models.TextField(default=None, verbose_name='传入参数'),
        ),
    ]
