# Generated by Django 2.2.3 on 2021-10-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view_permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViewCountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('call_time', models.IntegerField()),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view_permission.ViewModel')),
            ],
            options={
                'verbose_name': '视图请求计数表',
                'verbose_name_plural': '视图请求计数表',
            },
        ),
    ]
