# Generated by Django 2.2.3 on 2021-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_permission', '0003_permissionmodel_is_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='need_login',
            field=models.BooleanField(default=False, verbose_name='是否需要登录'),
        ),
    ]
