# Generated by Django 2.2.3 on 2021-09-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_permission', '0004_permissionmodel_need_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='req_info',
            field=models.TextField(default=None, verbose_name='传入参数'),
        ),
    ]
