# Generated by Django 2.2.3 on 2021-10-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_permission', '0004_auto_20211013_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPCacheModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'vp_cache',
            },
        ),
    ]
