# Generated by Django 2.2.3 on 2021-08-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permissionmodel',
            table='vp_permissions',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='vp_groups',
        ),
        migrations.AlterModelTable(
            name='viewmodel',
            table='vp_views',
        ),
    ]
